name: Example CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: images


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List files
        run: ls -la
